### PR TITLE
Add external volumes for rabbitmq and redis

### PR DESCRIPTION
**Pull request by romandemidov**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Is it really necessary to clutter the container with more volumes? You shouldn't run rabbitmq or postgres in the container anyway.

**Comment by agolybev** [comment]
hi @SuperSandro2000, I agree with you but our users claim us about storing information from RabbitMQ and Redis server. 
I support the idea about one process a container and I've made [a prototype](https://github.com/ONLYOFFICE/docker-ds). Unfortunately, it still under development and it can't be used in production.

**Comment by ShockwaveNN** [comment]
@agolybev I agree with @SuperSandro2000, most of user just copy paste command from readme, and got permission troubles or some kind other with volumes. I think readme should explicitly note, that "If you wanna use rabbit as volume - you should add `-v /app/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq` to docker run`
This should be an option, but not a default solution for all users

**Comment by agolybev** [comment]
@ShockwaveNN, The first and the shortest `docker run` command is in the paragraph above. `docker run` with directory mapping is under the "Storing Data" title so I think it's normal to mention all available options.  If followed your approach, we have to remove any command there and leave a list of options.

**Comment by ShockwaveNN** [comment]
@agolybev Agree with you, but maybe we should add some warning, that mounting a lot of volumes can cause some issues (especially permission error), so volumes should be used only if really needed

**Comment by SuperSandro2000** [comment]
> hi @SuperSandro2000, I agree with you but our users claim us about storing information from RabbitMQ and Redis server.
> I support the idea about one process a container and I've made [a prototype](https://github.com/ONLYOFFICE/docker-ds). Unfortunately, it still under development and it can't be used in production.

I just now realise what you are doing and WTF! why the hell did you include redid, postgres and rabbitmq in the image?!? There are official docker images for all those three services and they are really configured with no more than 5 variables reach. This would decrease the image size significantly and probably save a gigabyte storage on my server. 

This also would solve this entire PR.

**Pull request merged**
