### PR TITLE
Specify POSTGRESQL_SERVER_PORT for new databases

### PR DESCRIPTION
**Pull request by leo-lb**

### CODE REVIEW

**Comment by leo-lb** [comment]
Please note that this even affects setups with an external database that is not new (already set up with onlyoffice schema), because onlyoffice connects and checks for that schema during startup. That check attempt will time out and then run the rest of onlyoffice normally without any error whatsoever because the rest of the code correctly uses the provided port.

**Comment by agolybev** [comment]
Hi @leo-lb, thanks a lot.

**Comment by leo-lb** [comment]
Can you make a point release with this patch and update the docker image at Docker Hub?

**Comment by ShockwaveNN** [comment]
@leo-lb sorry, we currently almost ready to release 5.3.4, so we cannot postpone that.
We will include this change in 5.3.5 if we gonna release 5.3.5 (not sure)
But it definitely will be included in 5.4 (no exact date, sorry)

So I think best option for - is to build Docker image by yourself

**Comment by leo-lb** [comment]
> @leo-lb sorry, we currently almost ready to release 5.3.4, so we cannot postpone that.
> We will include this change in 5.3.5 if we gonna release 5.3.5 (not sure)
> But it definitely will be included in 5.4 (no exact date, sorry)
> 
> So I think best option for - is to build Docker image by yourself

It shouldnt cost you anything to backport this bugfix in the previous releases, there really is nothing to test, it just works. Building the docker image etc. is a PITA to maintain, it means I will need to think about switching back to your image later on my production systems.

**Comment by ShockwaveNN** [comment]
@leo-lb I agree about
> It shouldn't cost you anything to backport this bugfix in the previous releases

but our workflow is not optimized for it, because we literally want to release 5.3.4 tomorrow, and we should postpone it for several days if we include another fix

**Comment by leo-lb** [comment]
@ShockwaveNN 5.4.0 is released now! Fix has shipped! Thanks.

**Pull request merged**
