### PR TITLE
fix issue #96 ; 'Download failed' after upgrade to onlyoffice 

### PR DESCRIPTION
**Pull request by ReinerNippes**
Added $SSL_SELFSIGNED_CERTIFICATE to docker environment variables to set CoAuthoring.requestDefaults.rejectUnauthorized in /etc/onlyoffice/documentserver/local.json if using a selfsigned certificate.

### CODE REVIEW

**Comment by agolybev** [comment]
Hi @ReinerNippes, I agree with your changes but I absolutely disagree with the parameter name `SSL_SELFSIGNED_CERTIFICATE`. Because it could be associated with certificate settings for Nginx.
I'll add a change request for the pull request.

**Comment by ReinerNippes** [comment]
I'm fine with any name for that variable. And I agree that it's confusing. Too many certificates. ;-)

How about `REJECT_UNAUTHORIZED` or `REJECT_UNAUTHORIZED_STORAGE_SERVER`?

**Comment by ShockwaveNN** [comment]
Maybe `SSL_REJECT_UNAUTHORIZED` @agolybev

**Comment by ReinerNippes** [comment]
@agolybev This is absolutly OK. Do I have to do anything? 
I can't find any "Approve" button.

**Comment by agolybev** [comment]
Hi @ReinerNippes you have to make few changes on **your** branch `selfsigned_certificate `: 
- Rename new param to `REJECT_UNAUTHORIZED_STORAGE` in `README.md`
- Move description of the new param to the down of the list in `README.md`
- Rename `SSL_SELFSIGNED_CERTIFICATE` var to `REJECT_UNAUTHORIZED_STORAGE` in run-`document-server.sh`

**Comment by agolybev** [comment]
@ReinerNippes, I changed the pull request base to `develop`. Now it has conflicted files. To resolve this issue please merge branch `develop` into  `selfsigned_certificate` and resolve conflict changes in your repo.

**Comment by SuperSandro2000** [comment]
> To resolve this issue please merge branch `develop` into `selfsigned_certificate` and resolve conflict changes in your repo.

The better way would be to rebase your feature branch onto master.

**Comment by agolybev** [comment]
@SuperSandro2000  I moved base to `develop` on purpose according to a development procedure.

**Comment by agolybev** [comment]
I've remade it a little https://github.com/ONLYOFFICE/Docker-DocumentServer/commit/9eff99f618f033ba9986e62b5fff75ed5d24a0c0

**Pull request merged**
